echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27" 
echo "I am learning Git from now onwards"
echo "I am stud of devops"
echo "I'm gem of person using the git hub"
echo "HI THERE BE THERE bye bye bye"
echo "new folder"
echo "new folder2"
